/// Generated by AssetsRefGenerator on 2023/11/07
class Res {
  static const String splash_user = "assets/images/splash_user.json";
  static const String icon = "assets/icon/icon.png";
  static const String img = "assets/icon/img.png";
  static const String ios_icon_app = "assets/icon/ios_icon_app.png";
  static const String loading_summary = "assets/images/loading_summary.png";
  static const String head_splash = "assets/images/head_splash.png";
  static const String bot_splash = "assets/images/bot_splash.png";
  

}
